spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/server
    username: postgres
    password: Usuario123.
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true